//
//  Cards.swift
//  Cipher TCG
//
//  Created by Dylan Rothfeld on 1/16/18.
//  Copyright © 2018 Dylan Rothfeld. All rights reserved.
//

import UIKit

let s03_002 = Card(series: "S03-002ST",
                   name: "Successor of Hoshido, Ryoma",
                   rarity: "Starter Deck Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 10,
                   illustrator: "Clover K",
                   supportingSkill: none,
                   skills: [sacred_treasure_raijinto, i_do_not_like_to_give_up],
                   cardImageName: "S03-002ST.png")

let b01_046 = Card(series: "B01-046SR",
                   name: "Manakete Princess, Tiki",
                   rarity: "Secret Rare",
                   insignia: blade_of_light,
                   attack: 60,
                   support: 20,
                   illustrator: "Fuzichoco",
                   supportingSkill: none,
                   skills: [kind_hearted_dragon_princess, ancient_dragon_tribe_2, divine_stone],
                   cardImageName: "B01-046.png")

let b01_051 = Card(series: "B01-051SR",
                   name: "Exalted Prince, Chrom",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "Senri Kita",
                   supportingSkill: none,
                   skills: [vested_authority, exalted_falchion],
                   cardImageName: "B01-051.png")

let b01_054 = Card(series: "B01-054SR",
                   name: "Future Witness, Lucina",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "Masaki Hirooka",
                   supportingSkill: none,
                   skills: [defiant_of_destiny, parallel_falchion],
                   cardImageName: "B01-054.png")

let b01_057 = Card(series: "B01-057R",
                   name: "Exalted Strategist, Robin (Female)",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 20,
                   illustrator: "BISAI",
                   supportingSkill: none,
                   skills: [grandmaster_plan, all_according_to_plan],
                   cardImageName: "B01-057.png")

let b01_075 = Card(series: "B01-075SR",
                   name: "Cordelia: Pegasus Knight Paragon",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 50,
                   support: 30,
                   illustrator: "YangYang",
                   supportingSkill: none,
                   skills: [galeforce, handmade_javelins],
                   cardImageName: "B01-075.png")

let b01_078 = Card(series: "B01-078R",
                   name: "Wellspring of Youth, Nowi",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 50,
                   support: 20,
                   illustrator: "Pisuke",
                   supportingSkill: none,
                   skills: [young_manakete, ancient_dragon_tribe],
                   cardImageName: "B01-078.png")

let b02_001 = Card(series: "B02-001SR",
                   name: "Corrin (Male): Chosen Prince of the Godly Blade",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 20,
                   illustrator: "Kaoru Hagiya",
                   supportingSkill: none,
                   skills: [banner_of_light, untarnished_white_sword],
                   cardImageName: "B02-001.png")

let b02_003 = Card(series: "B02-003HN",
                   name: "Crown Prince of Hoshido, Corrin",
                   rarity: "High Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 20,
                   illustrator: "Yusuke Kozaki",
                   supportingSkill: heros_emblem,
                   skills: [nohrian_heart, noble_yato],
                   cardImageName: "B02-003.png")

let b02_006 = Card(series: "B02-006SR",
                   name: "Swordmaster of Roaring Thunder, Ryoma",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 10,
                   illustrator: "Rika Suzuki",
                   supportingSkill: none,
                   skills: [lightning_blade, unyielding_forces],
                   cardImageName: "B02-006.png")

let b02_008 = Card(series: "B02-008SR",
                   name: "Captain of the Red Lotus, Hinoka",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 60,
                   support: 30,
                   illustrator: "Mayo",
                   supportingSkill: none,
                   skills: [pep_talk, galloping_gallantry],
                   cardImageName: "B02-008.png")

let b02_009 = Card(series: "B02-009N",
                   name: "Hinoka: First Princess of Hoshido",
                   rarity: "Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 30,
                   illustrator: "Mayo",
                   supportingSkill: flying_emblem,
                   skills: [princess_of_hoshido],
                   cardImageName: "B02-009.png")

let b02_012 = Card(series: "B02-012SR",
                   name: "Sakura: Priestess of Love and War",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 60,
                   support: 20,
                   illustrator: "Tetsu Kurosawa",
                   supportingSkill: none,
                   skills: [cascading_blossoms_of_restoration, wingbane],
                   cardImageName: "B02-012.png")

let b02_030 = Card(series: "B02-030SR",
                   name: "Capable Maid, Felicia",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 60,
                   support: 20,
                   illustrator: "HACCAN",
                   supportingSkill: none,
                   skills: [here_i_go, i_wont_go_easy],
                   cardImageName: "B02-030.png")

let b02_041 = Card(series: "B02-041HN",
                   name: "Kana (Female): White Dragon Princess",
                   rarity: "High Normal",
                   insignia: hoshido,
                   attack: 50,
                   support: 20,
                   illustrator: "cuboon",
                   supportingSkill: none,
                   skills: [reckless_power, blood_of_the_holy_dragon],
                   cardImageName: "B02-041.png")

let b02_051 = Card(series: "B02-051SR",
                   name: "Chosen Princess of the Godly Blade, Corrin",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 70,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [blood_stained_dark_sword, march_of_darkness],
                   cardImageName: "B02-051.png")

let b02_056 = Card(series: "B02-056SR",
                   name: "Pitch Dark Paladin, Xander",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 70,
                   support: 10,
                   illustrator: "Rika Suzuki",
                   supportingSkill: none,
                   skills: [unrestrained_rule, disjointed_fate],
                   cardImageName: "B02-056.png")

let b02_060 = Card(series: "B02-060SR",
                   name: "Prince of Darkness, Leo",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 60,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [brynhildr, soulcrushing_darkness],
                   cardImageName: "B02-060.png")

let b03_032 = Card(series: "B03-032R",
                   name: "Swift Lance of Liberation, Nephenee",
                   rarity: "Rare",
                   insignia: medallion,
                   attack: 70,
                   support: 10,
                   illustrator: "Raita Kazama",
                   supportingSkill: none,
                   skills: [impaling_princess, tempered_wrath],
                   cardImageName: "B03-032.png")

let b03_043 = Card(series: "B03-043R",
                   name: "King of Phoenicis, Tibarn",
                   rarity: "Rare",
                   insignia: medallion,
                   attack: 60,
                   support: 20,
                   illustrator: "Ayaka Suzuki",
                   supportingSkill: none,
                   skills: [sky_glider, roar_of_the_king],
                   cardImageName: "B03-043.png")

let b03_044 = Card(series: "B03-044R",
                   name: "King of Kilvas, Naesala",
                   rarity: "Rare",
                   insignia: medallion,
                   attack: 60,
                   support: 20,
                   illustrator: "Mikihiro Taguchi",
                   supportingSkill: none,
                   skills: [vortex, job_well_done],
                   cardImageName: "B03-044.png")

let b03_046 = Card(series: "B03-046R",
                   name: "Awakened Heron Princess, Leanne",
                   rarity: "Rare",
                   insignia: medallion,
                   attack: 10,
                   support: 20,
                   illustrator: "Ayaka Suzuki",
                   supportingSkill: miracle_emblem,
                   skills: [blessing, sleeping_beauty],
                   cardImageName: "B03-046.png")

let b03_047 = Card(series: "B03-047SR",
                   name: "Demon in Blessed Armor, Black Knight",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 80,
                   support: 0,
                   illustrator: "Daisuke Izuka",
                   supportingSkill: none,
                   skills: [divine_blade_alondite, mantle],
                   cardImageName: "B03-047.png")

let b03_051 = Card(series: "B03-051SR",
                   name: "Godly Child of the Final Light Flame, Corrin",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [flaming_blade_of_light_and_darkness, omega_yato],
                   cardImageName: "B03-051.png")

let b03_052 = Card(series: "B03-052HN",
                   name: "Princess of Hoshido, Corrin",
                   rarity: "High Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: heros_emblem,
                   skills: [grim_yato],
                   cardImageName: "B03-052.png")

let b03_053 = Card(series: "B03-053SR",
                   name: "Diva of Dawn, Azura",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 60,
                   support: 10,
                   illustrator: "Senri Kita",
                   supportingSkill: none,
                   skills: [song_of_fortunes, princess_of_the_nation, light_road_to_the_invisible_kingdom],
                   cardImageName: "B03-053.png")

let b03_063 = Card(series: "B03-063R",
                   name: "Nightingale Warrior, Shigure",
                   rarity: "Rare",
                   insignia: hoshido,
                   attack: 50,
                   support: 30,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [cry_of_the_pegasus, resounding_anthem],
                   cardImageName: "B03-063.png")

let b03_067 = Card(series: "B03-067HN",
                   name: "Natural Hunter, Kiragi",
                   rarity: "High Normal",
                   insignia: hoshido,
                   attack: 50,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [prince_of_gales, wingbane],
                   cardImageName: "B03-067.png")

let b03_068 = Card(series: "B03-068N",
                   name: "Optimistic Archer, Kiragi",
                   rarity: "Normal",
                   insignia: hoshido,
                   attack: 30,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: attack_emblem,
                   skills: [wild_prince, wingbane],
                   cardImageName: "B03-068.png")

let b03_072 = Card(series: "B03-072R",
                   name: "Thread of Gold, Selkie",
                   rarity: "Rare",
                   insignia: hoshido,
                   attack: 60,
                   support: 10,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [whos_that_whos_that, masquerade],
                   cardImageName: "B03-072.png")

let b03_078 = Card(series: "B03-078SR",
                   name: "Diva of Dusk, Azura",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 60,
                   support: 10,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [song_of_destruction, princess_of_the_nation, dark_road_to_the_invisible_kingdom],
                   cardImageName: "B03-078.png")

let b03_086 = Card(series: "B03-086R",
                   name: "Black Dragon Princess, Kana",
                   rarity: "Rare",
                   insignia: nohr,
                   attack: 60,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [overwhelming_power, lineage_of_the_elder_dragon],
                   cardImageName: "B03-086.png")

let b03_091 = Card(series: "B03-091R",
                   name: "Chivalrous Thief, Nina",
                   rarity: "Rare",
                   insignia: nohr,
                   attack: 50,
                   support: 10,
                   illustrator: "daigoman",
                   supportingSkill: none,
                   skills: [youthful_discernment, wingbane],
                   cardImageName: "B03-091.png")

let b03_092 = Card(series: "B03-092N",
                   name: "Delusional Escapist, Nina",
                   rarity: "Normal",
                   insignia: nohr,
                   attack: 30,
                   support: 10,
                   illustrator: "daigoman",
                   supportingSkill: thief_emblem,
                   skills: [lecherous_lockpicking, wingbane],
                   cardImageName: "B03-092.png")

let b04_001 = Card(series: "B04-001SR",
                   name: "The Golden Idol, Tsubasa Oribe",
                   rarity: "Secret Rare",
                   insignia: blade_of_light,
                   attack: 70,
                   support: 20,
                   illustrator: "Masaki Hiiroka",
                   supportingSkill: none,
                   skills: [grand_finale, fly_windswept_passions],
                   cardImageName: "B04-001.png")

let b04_018 = Card(series: "B04-018SR",
                   name: "Lambent Hero-King, Marth",
                   rarity: "Secret Rare",
                   insignia: blade_of_light,
                   attack: 70,
                   support: 20,
                   illustrator: "Maki Hakoda",
                   supportingSkill: none,
                   skills: [leader_of_the_ragtag, falchion],
                   cardImageName: "B04-018.png")

let b04_063 = Card(series: "B04-063SR",
                   name: "Iris of Destiny, Lucina",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "Fuzichoco",
                   supportingSkill: none,
                   skills: [hands_of_fate, enlightened_edge],
                   cardImageName: "B04-063.png")

let b04_065 = Card(series: "B04-065SR",
                   name: "Exalted Grandmaster, Robin",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "lack",
                   supportingSkill: none,
                   skills: [rally_spectrum, two_steps_ahead],
                   cardImageName: "B04-065.png")

let b04_072 = Card(series: "B04-072SR",
                   name: "Cordelia: Pure Genius",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 30,
                   illustrator: "daigoman",
                   supportingSkill: none,
                   skills: [empyrean_goddess, intermezzo],
                   cardImageName: "B04-072.png")

let b04_092 = Card(series: "B04-092R",
                   name: "Cynthia: Wings of Justice",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 50,
                   support: 30,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [your_hero_arrives, now_i_gracefull_depart],
                   cardImageName: "B04-092.png")

let b05_051 = Card(series: "B05-051SR",
                   name: "Priestess of Hope, Micaiah",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 60,
                   support: 20,
                   illustrator: "Tetsu Kurosawa",
                   supportingSkill: none,
                   skills: [shine, priestess_of_dawn],
                   cardImageName: "B05-051.png")

let b05_077 = Card(series: "B05-077R",
                   name: "Patriotic War Princess, Nephenee",
                   rarity: "Rare",
                   insignia: medallion,
                   attack: 60,
                   support: 10,
                   illustrator: "Daigoman",
                   supportingSkill: none,
                   skills: [furious_point, javelin],
                   cardImageName: "B05-077.png")

let b05_082 = Card(series: "B05-082SR",
                   name: "Lancer General, Geoffrey",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 70,
                   support: 10,
                   illustrator: "Rika Suzuki",
                   supportingSkill: none,
                   skills: [glory_to_the_queen, commander_of_the_royal_guards],
                   cardImageName: "B05-082.png")

let b05_089 = Card(series: "B05-089SR",
                   name: "Radiant Hero, Ike",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 70,
                   support: 20,
                   illustrator: "Senri Kita",
                   supportingSkill: none,
                   skills: [aether, memories_of_war],
                   cardImageName: "B05-089.png")

let b06_001 = Card(series: "B06-001SR",
                   name: "The Warrior of Light's Heir, Sigurd",
                   rarity: "Secret Rare",
                   insignia: holy_war_flag,
                   attack: 70,
                   support: 20,
                   illustrator: "Rika Suzuki",
                   supportingSkill: none,
                   skills: [darkness_illuminating_warrior, sacred_blade_tyrfing],
                   cardImageName: "B06-001.png")

let b06_004 = Card(series: "B06-004SR",
                   name: "Maiden of Destiny, Deirdre",
                   rarity: "Secret Rare",
                   insignia: holy_war_flag,
                   attack: 60,
                   support: 20,
                   illustrator: "Fuzichoco",
                   supportingSkill: none,
                   skills: [taboo_surpassing_love, seal_of_naga],
                   cardImageName: "B06-004.png")

let b06_006 = Card(series: "B06-006SR",
                   name: "Aura-Enshrouded Lancer, Quan",
                   rarity: "Secret Rare",
                   insignia: holy_war_flag,
                   attack: 70,
                   support: 10,
                   illustrator: "Sachiko Wada",
                   supportingSkill: none,
                   skills: [aura_of_nova, thracian_besting_lance],
                   cardImageName: "B06-006.png")

let b06_018 = Card(series: "B06-018HN",
                   name: "Shining Flame of Kindness, Azel",
                   rarity: "High Normal",
                   insignia: holy_war_flag,
                   attack: 50,
                   support: 20,
                   illustrator: "Unknown",
                   supportingSkill: none,
                   skills: [plains_galloper, canto],
                   cardImageName: "B06-018.png")

let b06_051 = Card(series: "B06-051SR",
                   name: "Unifier of the Kingdom of Nohr, Xander",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 70,
                   support: 20,
                   illustrator: "Rika Suzuki",
                   supportingSkill: none,
                   skills: [godly_wind, stage_for_a_singular_duel, dragons_pulse],
                   cardImageName: "B06-051.png")

let b06_054 = Card(series: "B06-054SR",
                   name: "Beautiful Obsidian Princess, Camilla",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 60,
                   support: 30,
                   illustrator: "Mayo",
                   supportingSkill: none,
                   skills: [eruption, obsidian_mist],
                   cardImageName: "B06-054.png")

let b06_056 = Card(series: "B06-056SR",
                   name: "Younger Dark Prince of Chilling Magic, Leo",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 60,
                   support: 20,
                   illustrator: "Aoji",
                   supportingSkill: none,
                   skills: [terrorizing_fear, chilling_miasma],
                   cardImageName: "B06-056.png")

let b06_062 = Card(series: "B06-062R",
                   name: "The Deadly, Beruka",
                   rarity: "Rare",
                   insignia: nohr,
                   attack: 50,
                   support: 30,
                   illustrator: "Saori Toyota",
                   supportingSkill: none,
                   skills: [all_or_nothing, death_gale],
                   cardImageName: "B06-062.png")

let b06_063 = Card(series: "B06-063N",
                   name: "Flying Assassin, Beruka",
                   rarity: "Normal",
                   insignia: nohr,
                   attack: 30,
                   support: 30,
                   illustrator: "Saori Toyota",
                   supportingSkill: flying_emblem,
                   skills: [commander_of_the_kamikaze_unit],
                   cardImageName: "B06-063.png")

let b07_051 = Card(series: "B07-051SR",
                   name: "Unifier of the Kingdom of Hoshido, Ryoma",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 20,
                   illustrator: "Rika Suzuki",
                   supportingSkill: none,
                   skills: [summoning_thunder, stage_for_decisive_battle, voice_of_dragons],
                   cardImageName: "B07-051.png")

let b07_053 = Card(series: "B07-053HN",
                   name: "Warrior of Hoshido, Ryoma",
                   rarity: "High Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 10,
                   illustrator: "Tada",
                   supportingSkill: attack_emblem,
                   skills: [royal_familys_blood],
                   cardImageName: "B07-053.png")

let b07_056 = Card(series: "B07-056SR",
                   name: "Prince of Brilliant Winds, Takumi",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 60,
                   support: 20,
                   illustrator: "Aoji",
                   supportingSkill: none,
                   skills: [parting_the_sea, stormy_plains, wingbane],
                   cardImageName: "B07-056.png")

let b07_058 = Card(series: "B07-058SR",
                   name: "Dancing in Hoshidan Bloom, Sakura",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 60,
                   support: 20,
                   illustrator: "Tetsu Kurosawa",
                   supportingSkill: none,
                   skills: [recovery, blessed_sakura_storm],
                   cardImageName: "B07-058.png")

let b07_064 = Card(series: "B07-064R",
                   name: "Careless Kinshi Knight, Setsuna",
                   rarity: "Rare",
                   insignia: hoshido,
                   attack: 30,
                   support: 30,
                   illustrator: "BISAI",
                   supportingSkill: none,
                   skills: [airhead, setsunas_yumi, wingbane],
                   cardImageName: "B07-064.png")

let b07_068 = Card(series: "B07-068R",
                   name: "The Unyielding Girl, Hana",
                   rarity: "Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 10,
                   illustrator: "daigoman",
                   supportingSkill: none,
                   skills: [swords_beat_axes_and_bows, axes_beat_lances_and_shurikens, lances_beat_swords_and_tomes],
                   cardImageName: "B07-068.png")

let b07_086 = Card(series: "B07-086HN",
                   name: "Wild Archery, Kiragi",
                   rarity: "High Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 30,
                   illustrator: "Kokon Konfuzi",
                   supportingSkill: none,
                   skills: [dragon_vein_whiff, wingbane],
                   cardImageName: "B07-086.png")

let b08_004 = Card(series: "B08-004R",
                   name: "Divine Dragon's Exalt, Lucina",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 20,
                   illustrator: "Tetsu Kurosawa",
                   supportingSkill: none,
                   skills: [lord_of_the_future, inexhaustible_wish, guidance_of_the_brand],
                   cardImageName: "B08-004.png")

let b08_001 = Card(series: "B08-001SR",
                   name: "Sacred Sovereign of Hope, Chrom",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "Kotaro Yamada",
                   supportingSkill: none,
                   skills: [future_changing_bonds, hopeful_future],
                   cardImageName: "B08-001.png")

let b08_002 = Card(series: "B08-002SR",
                   name: "Undead King of Despair, Chrom",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 80,
                   support: 0,
                   illustrator: "Setsu",
                   supportingSkill: none,
                   skills: [awaken_the_dead, cursed_army_of_despair, land_of_the_risen],
                   cardImageName: "B08-002.png")

let b08_006 = Card(series: "B08-006SR",
                   name: "Legendary Tactician, Robin (Female)",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "BISAI",
                   supportingSkill: none,
                   skills: [the_verge_of_histroy, strategy_of_hope, invsiible_ties],
                   cardImageName: "B08-006.png")

let b08_009 = Card(series: "B08-009SR",
                   name: "The Exalt's Guardian Knight, Frederick",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 10,
                   illustrator: "Kaoru Hagiya",
                   supportingSkill: none,
                   skills: [divine_ride, the_silver_knightly_captain, ill_defend_you_to_the_last],
                   cardImageName: "B08-009.png")

let b08_010 = Card(series: "B08-010R",
                   name: "Head of House Virion, Virion",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 20,
                   illustrator: "Yamada Kotarou",
                   supportingSkill: none,
                   skills: [dukes_conquest, bowbreaker, wingbane],
                   cardImageName: "B08-010.png")

let b08_039 = Card(series: "B08-039R",
                   name: "Immortal Voice, Tiki",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 50,
                   support: 20,
                   illustrator: "Fuzichoco",
                   supportingSkill: none,
                   skills: [rite_of_awakening, divine_dragons_awakening, long_lived_dragon_clan],
                   cardImageName: "B08-039.png")

let b08_047 = Card(series: "B08-047N",
                   name: "Risen: Defiled Soldier",
                   rarity: "Normal",
                   insignia: mark_of_naga,
                   attack: 0,
                   support: 0,
                   illustrator: "aogachou",
                   supportingSkill: despair_emblem,
                   skills: [army_of_risen],
                   cardImageName: "B08-047.png")

let b08_048 = Card(series: "B08-048SR",
                   name: "Grima: Baleful Dragon",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 0,
                   illustrator: "cuboon",
                   supportingSkill: none,
                   skills: [deitys_vessel, the_grimleal, dragonskin],
                   cardImageName: "B08-048.png")

let b09_076 = Card(series: "B09-076SR",
                   name: "Regal-Fanged Successor, Skrimir",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 80,
                   support: 10,
                   illustrator: "Senri Kita",
                   supportingSkill: none,
                   skills: [regalia, crimson_mane, showdown_roar],
                   cardImageName: "B09-076.png")

let b09_085 = Card(series: "B09-085SR",
                   name: "King of Gallia, Caineghis",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 50,
                   support: 20,
                   illustrator: "Fuzichoco",
                   supportingSkill: none,
                   skills: [nurture_a_wish, pink_scaled_dragon_girl],
                   cardImageName: "B09-085.png")

let b09_090 = Card(series: "B09-090R",
                   name: "King of Gallia, Caineghis",
                   rarity: "Rare",
                   insignia: medallion,
                   attack: 100,
                   support: 10,
                   illustrator: "Kita Senri",
                   supportingSkill: none,
                   skills: [race_transcending_alliance],
                   cardImageName: "B09-090.png")

let b10_051 = Card(series: "B10-051SR",
                   name: "Night-Transcending Princess, Kana",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 20,
                   illustrator: "lack",
                   supportingSkill: none,
                   skills: [warm_strength, our_yato],
                   cardImageName: "B10-051.png")

let b10_052 = Card(series: "B10-052N",
                   name: "Girl of the White Path, Kana",
                   rarity: "Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 20,
                   illustrator: "lack",
                   supportingSkill: hope_emblem,
                   skills: [in_the_white_light],
                   cardImageName: "B10-052.png")

let b10_053 = Card(series: "B10-053SR",
                   name: "Night-Transcending Prince, Kana",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 70,
                   support: 20,
                   illustrator: "lack",
                   supportingSkill: none,
                   skills: [unyielding_hope, our_yato],
                   cardImageName: "B10-053.png")

let b10_054 = Card(series: "B10-054N",
                   name: "Boy of the Dark Path, Kana",
                   rarity: "Normal",
                   insignia: nohr,
                   attack: 40,
                   support: 20,
                   illustrator: "lack",
                   supportingSkill: hope_emblem,
                   skills: [embrace_the_dark],
                   cardImageName: "B10-054.png")

let b10_055 = Card(series: "B10-055SR",
                   name: "Divine Son of the Dazzling Dawn Dragon, Corrin",
                   rarity: "Secret Rare",
                   insignia: hoshido,
                   attack: 80,
                   support: 20,
                   illustrator: "Ryuutetu",
                   supportingSkill: none,
                   skills: [gleaming_white_scale, dawning_dragon_blood],
                   cardImageName: "B10-055.png")

let b10_057 = Card(series: "B10-057SR",
                   name: "Divine Daughter of the Darkening Dusk Dragon, Corrin",
                   rarity: "Secret Rare",
                   insignia: nohr,
                   attack: 80,
                   support: 20,
                   illustrator: "Ryuutetu",
                   supportingSkill: none,
                   skills: [wings_of_darkness_neverending, dusking_dragon_blood],
                   cardImageName: "B10-057.png")

let b10_059 = Card(series: "B10-059R",
                   name: "End of the Ideal Path, Shigure",
                   rarity: "Rare",
                   insignia: nohr,
                   attack: 60,
                   support: 30,
                   illustrator: "Kaoru Hagiya / Misei Ito",
                   supportingSkill: none,
                   skills: [lost_in_the_waves, forbidden_lyric, treasured_memory],
                   cardImageName: "B10-059.png")

let b10_060 = Card(series: "B10-060N",
                   name: "Canyon-Wandering Soul, Shigure",
                   rarity: "Normal",
                   insignia: nohr,
                   attack: 30,
                   support: 30,
                   illustrator: "Unknown",
                   supportingSkill: flying_emblem,
                   skills: [bequeathed_necklace],
                   cardImageName: "B10-060.png")

let b10_061 = Card(series: "B10-061R",
                   name: "Ephemeral Songstress, Azura",
                   rarity: "Rare",
                   insignia: nohr,
                   attack: 0,
                   support: 20,
                   illustrator: "cuboon / Misei Ito",
                   supportingSkill: none,
                   skills: [the_changing_tide, watchful_eye],
                   cardImageName: "B10-061.png")

let b10_064 = Card(series: "B10-064R",
                   name: "Fox in Black, Selkie",
                   rarity: "Rare",
                   insignia: hoshido,
                   attack: 70,
                   support: 10,
                   illustrator: "Tetsu Kurosawa",
                   supportingSkill: none,
                   skills: [everybody_dance, kitsunes_dancing_beat],
                   cardImageName: "B10-064.png")

let b10_065 = Card(series: "B10-065N",
                   name: "Simple Fox Girl, Selkie",
                   rarity: "Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 10,
                   illustrator: "Tetsu Kurosawa",
                   supportingSkill: attack_emblem,
                   skills: [i_found_you],
                   cardImageName: "B10-065.png")

let b10_068 = Card(series: "B10-068HN",
                   name: "Flawless Winged Archer, Caeldori",
                   rarity: "High Normal",
                   insignia: hoshido,
                   attack: 40,
                   support: 30,
                   illustrator: "HMK84",
                   supportingSkill: none,
                   skills: [perfect_arragement, prodigy, wingbane],
                   cardImageName: "B10-068.png")

let b10_076 = Card(series: "B10-076R",
                   name: "Rehearsal of a Turnabout Victory, Ophelia",
                   rarity: "Rare",
                   insignia: nohr,
                   attack: 60,
                   support: 20,
                   illustrator: "Sakura Miwabe",
                   supportingSkill: none,
                   skills: [maidens_supreme_secret_weapon, missiletainn_2],
                   cardImageName: "B10-076.png")

let b10_081 = Card(series: "B10-081HN",
                   name: "Bright Smile, Soleil",
                   rarity: "High Normal",
                   insignia: nohr,
                   attack: 40,
                   support: 10,
                   illustrator: "Sachiko Wada",
                   supportingSkill: attack_emblem,
                   skills: [soleil_the_flirtatious, ill_protect_you],
                   cardImageName: "B10-081.png")

let b10_086 = Card(series: "B10-086HN",
                   name: "Crazed Silent Dragon, Anankos",
                   rarity: "High Normal",
                   insignia: nohr,
                   attack: 0,
                   support: 0,
                   illustrator: "Yoneko",
                   supportingSkill: none,
                   skills: [corrupted_paradise, curse_twisted_dream],
                   cardImageName: "B10-086.png")

let b10_095 = Card(series: "B10-095R",
                   name: "Dark-Garbed Mage Knight, Bruno",
                   rarity: "Rare",
                   insignia: colorless,
                   attack: 50,
                   support: 20,
                   illustrator: "Setsu",
                   supportingSkill: none,
                   skills: [valaskjalf, impregnable_force],
                   cardImageName: "B10-095.png")

let b10_097 = Card(series: "B10-097SR",
                   name: "Detached Princess, Veronica",
                   rarity: "Secret Rare",
                   insignia: colorless,
                   attack: 50,
                   support: 20,
                   illustrator: "Geso Umiu",
                   supportingSkill: none,
                   skills: [princess_of_death, ill_shut_you_out, elivagar],
                   cardImageName: "B10-097.png")

let b11_001 = Card(series: "B11-001SR",
                   name: "Restoration Queen, Eirika",
                   rarity: "Secret Rare",
                   insignia: divine_weapons,
                   attack: 70,
                   support: 20,
                   illustrator: "Sachiko Wada",
                   supportingSkill: none,
                   skills: [two_heroes_eirika, courage_to_confront, sieglindes_rays],
                   cardImageName: "B11-001.png")

let b11_002 = Card(series: "B11-002R",
                   name: "Eirika: Princess of the Sacred Storm Blade",
                   rarity: "Rare",
                   insignia: divine_weapons,
                   attack: 60,
                   support: 20,
                   illustrator: "Rika Suzuki",
                   supportingSkill: enduring_command,
                   skills: [stormlike_resolve, lunar_brace],
                   cardImageName: "B11-002.png")

let b11_003 = Card(series: "B11-003",
                   name: "Eirika: Princess of Renais",
                   rarity: "High Normal",
                   insignia: divine_weapons,
                   attack: 40,
                   support: 20,
                   illustrator: "Sachiko Wada",
                   supportingSkill: encouragement_emblem,
                   skills: [],
                   cardImageName: "B11-003.png")

let b11_004 = Card(series: "B11-004SR",
                   name: "Restoration King, Ephraim",
                   rarity: "Secret Rare",
                   insignia: divine_weapons,
                   attack: 70,
                   support: 20,
                   illustrator: "Sachiko Wada",
                   supportingSkill: none,
                   skills: [two_heroes_ephraim, cleaving_justice, legendary_siegmund],
                   cardImageName: "B11-004.png")

let b11_005 = Card(series: "B11-005R",
                   name: "Ephraim: Prince of the Blazing Brave Lance",
                   rarity: "Rare",
                   insignia: divine_weapons,
                   attack: 60,
                   support: 20,
                   illustrator: "Rika Suzuki",
                   supportingSkill: invincible_command,
                   skills: [flamelike_strength, solar_brace],
                   cardImageName: "B11-005.png")

let b11_006 = Card(series: "B11-006HN",
                   name: "Ephraim: Prince of Renais",
                   rarity: "High Normal",
                   insignia: divine_weapons,
                   attack: 40,
                   support: 20,
                   illustrator: "Sachiko Wada",
                   supportingSkill: heros_emblem,
                   skills: [],
                   cardImageName: "B11-006.png")

let b11_007 = Card(series: "B11-007N",
                   name: "Seth: Silver Knight",
                   rarity: "Normal",
                   insignia: divine_weapons,
                   attack: 70,
                   support: 10,
                   illustrator: "Tomohide Takaya",
                   supportingSkill: none,
                   skills: [kingdom_protecting_blade, the_kind_princesss_knight],
                   cardImageName: "B11-007.png")

let b11_008 = Card(series: "B11-008HN",
                   name: "Vanessa: Dutiful Rider",
                   rarity: "High Normal",
                   insignia: divine_weapons,
                   attack: 50,
                   support: 30,
                   illustrator: "40hara",
                   supportingSkill: none,
                   skills: [escort_duty, javelin],
                   cardImageName: "B11-008.png")

let b11_009 = Card(series: "B11-009N",
                   name: "Vanessa: Dilligent Pegasus Knight",
                   rarity: "Normal",
                   insignia: divine_weapons,
                   attack: 30,
                   support: 30,
                   illustrator: "40hara",
                   supportingSkill: flying_emblem,
                   skills: [winged_deliverer],
                   cardImageName: "B11-009.png")

let b11_010 = Card(series: "B11-010HN",
                   name: "Ross: His Father's Son",
                   rarity: "High Normal",
                   insignia: divine_weapons,
                   attack: 60,
                   support: 10,
                   illustrator: "Nekobayashi",
                   supportingSkill: none,
                   skills: [the_villages_finest_fighter, sword_smashing_axe, hatchet],
                   cardImageName: "B11-010.png")

let b11_011 = Card(series: "B11-011N",
                   name: "Ross: Son of Garcia",
                   rarity: "Normal",
                   insignia: divine_weapons,
                   attack: 30,
                   support: 10,
                   illustrator: "Nekobayashi",
                   supportingSkill: tempered_emblem,
                   skills: [aspirational_back],
                   cardImageName: "B11-011.png")

let b11_020 = Card(series: "B11-020SR",
                   name: "Tempest King, Joshua",
                   rarity: "Secret Rare",
                   insignia: divine_weapons,
                   attack: 70,
                   support: 10,
                   illustrator: "nNekoRa",
                   supportingSkill: none,
                   skills: [oath_sworn_audhulma, lets_have_us_a_little_wager],
                   cardImageName: "B11-020.png")

let b11_041 = Card(series: "B11-041R",
                   name: "Great Dragon, Myrrh",
                   rarity: "Rare",
                   insignia: divine_weapons,
                   attack: 50,
                   support: 20,
                   illustrator: "Fumi",
                   supportingSkill: none,
                   skills: [eternally_young_savior, ancient_dragonkin],
                   cardImageName: "B11-041.png")

let b11_073 = Card(series: "B11-073HN",
                   name: "Flickering Memory of Love, Rinea",
                   rarity: "High Normal",
                   insignia: blade_of_light,
                   attack: 50,
                   support: 20,
                   illustrator: "Azusa",
                   supportingSkill: none,
                   skills: [inferno_of_love, dance_in_purgatory],
                   cardImageName: "B11-073.png")

let b11_076 = Card(series: "B11-076SR",
                   name: "Shining Sun Prince, Rowan",
                   rarity: "Secret Rare",
                   insignia: colorless,
                   attack: 70,
                   support: 20,
                   illustrator: "Azusa",
                   supportingSkill: none,
                   skills: [right_leave_it_to_me, warriors_enliron, youre_firing_me_up],
                   cardImageName: "B11-076.png")

let b11_079 = Card(series: "B11-079SR",
                   name: "Beautiful Sunflower Princess, Lianna",
                   rarity: "Secret Rare",
                   insignia: colorless,
                   attack: 70,
                   support: 20,
                   illustrator: "Fuzichoco",
                   supportingSkill: none,
                   skills: [here_i_go_2, radiant_facinna, the_light_of_hope],
                   cardImageName: "B11-079.png")

let b11_093 = Card(series: "B11-093SR",
                   name: "Awoken Daughter of the Dragon Ruler, Tiki",
                   rarity: "Secret Rare",
                   insignia: colorless,
                   attack: 70,
                   support: 20,
                   illustrator: "Kawasumi",
                   supportingSkill: none,
                   skills: [tikis_turn, dragons_growing_power, divine_dragon_princess],
                   cardImageName: "B11-093.png")

let b12_001 = Card(series: "B12-001SR",
                   name: "Radiant Vanguard, Ike",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 0,
                   support: 20,
                   illustrator: "Senri Kita",
                   supportingSkill: none,
                   skills: [legendary_swordplay, ragnells_aura, ceaseless_challenger],
                   cardImageName: "B12-001.png")

let b12_002 = Card(series: "B12-002SR",
                   name: "Nightmarish Rampaging Hero, Ike",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 100,
                   support: 0,
                   illustrator: "Senri Kita",
                   supportingSkill: none,
                   skills: [forbidden_medallion, raging_power, rampage],
                   cardImageName: "B12-002.png")

let b12_003 = Card(series: "B12-003N",
                   name: "Ike: Youth Becoming a Hero",
                   rarity: "Normal",
                   insignia: medallion,
                   attack: 40,
                   support: 20,
                   illustrator: "Senri Kita",
                   supportingSkill: heros_emblem,
                   skills: [maturing_swordsmanship],
                   cardImageName: "B12-003.png")

let b12_004 = Card(series: "B12-004SR",
                   name: "Mist: Ordered Knight of Healing",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 70,
                   support: 20,
                   illustrator: "Fuzichoco",
                   supportingSkill: none,
                   skills: [warm_singing, spring_breeze_florete],
                   cardImageName: "B12-004.png")

let b12_005 = Card(series: "B12-005N",
                   name: "Mist: Medallion-Bearing Girl",
                   rarity: "Normal",
                   insignia: medallion,
                   attack: 20,
                   support: 20,
                   illustrator: "Sachiko Wada",
                   supportingSkill: miracle_emblem,
                   skills: [defeat_rejecting_heart, heal],
                   cardImageName: "B12-005.png")

let b12_006 = Card(series: "B12-006R",
                   name: "Greil: Unending Night of Grief",
                   rarity: "Rare",
                   insignia: medallion,
                   attack: 80,
                   support: 0,
                   illustrator: "Akira Fujikawa",
                   supportingSkill: none,
                   skills: [tempestuous_edge, sinister_impulse],
                   cardImageName: "B12-006.png")

let b12_007 = Card(series: "B12-007N",
                   name: "Gawain: Sword Knight of Daein",
                   rarity: "Normal",
                   insignia: medallion,
                   attack: 40,
                   support: 10,
                   illustrator: "Kita Senri",
                   supportingSkill: attack_emblem,
                   skills: [a_happy_rendezvous, mercenary_leader_to_be],
                   cardImageName: "B12-007.png")

let b12_008 = Card(series: "B12-008HN",
                   name: "Elena: Keeper of the Medallion",
                   rarity: "High Normal",
                   insignia: medallion,
                   attack: 50,
                   support: 20,
                   illustrator: "Kita Senri",
                   supportingSkill: none,
                   skills: [soul_soothing_singing, beloved_husband],
                   cardImageName: "B12-008.png")

let b12_009 = Card(series: "B12-009N",
                   name: "Elena: Serene-Hearted Cleric",
                   rarity: "Normal",
                   insignia: medallion,
                   attack: 30,
                   support: 20,
                   illustrator: "Kita Senri",
                   supportingSkill: miracle_emblem,
                   skills: [ordered_hearts_encouragement],
                   cardImageName: "B12-009.png")

let b12_010 = Card(series: "B12-010SR",
                   name: "Micaiah: Goddess-Possessed Maiden",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 60,
                   support: 20,
                   illustrator: "Kaoru Hagiya",
                   supportingSkill: none,
                   skills: [blessings_of_yune, heart_of_the_goddess_of_chaos],
                   cardImageName: "B12-010.png")

let b12_011 = Card(series: "B12-011N",
                   name: "Micaiah: Silver-Haired Mage General",
                   rarity: "Normal",
                   insignia: medallion,
                   attack: 50,
                   support: 20,
                   illustrator: "Sakura Miwabe",
                   supportingSkill: none,
                   skills: [path_to_victory],
                   cardImageName: "B12-011.png")

let b12_012 = Card(series: "B12-012N",
                   name: "Micaiah: Maiden of Miracles",
                   rarity: "Normal",
                   insignia: medallion,
                   attack: 30,
                   support: 20,
                   illustrator: "Niji",
                   supportingSkill: fate_emblem,
                   skills: [bond_of_dawn],
                   cardImageName: "B12-012.png")

let b12_037 = Card(series: "B12-037SR",
                   name: "Fearsome Blade General, Black Knight",
                   rarity: "Secret Rare",
                   insignia: medallion,
                   attack: 80,
                   support: 0,
                   illustrator: "Daisuke Izuka",
                   supportingSkill: none,
                   skills: [miasma_of_alondite, end_heralding_holy_sword],
                   cardImageName: "B12-037.png")

let b12_051 = Card(series: "B12-051R",
                   name: "Awakened Justice, Chrom",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "Aoji",
                   supportingSkill: none,
                   skills: [army_of_justice, immortal_falchion],
                   cardImageName: "B12-051.png")

let b12_053 = Card(series: "B12-053R",
                   name: "Future-Wishing Exalted Eye, Lucina",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 20,
                   illustrator: "Yusuke Kozaki",
                   supportingSkill: none,
                   skills: [exalted_eyed_princess, immortal_falchion],
                   cardImageName: "B12-053.png")

let b12_054 = Card(series: "B12-054SR",
                   name: "Holy Princess, Lissa",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 20,
                   illustrator: "Tetsu Kurosawa",
                   supportingSkill: none,
                   skills: [ive_got_a_trick_up_my_sleeve, royal_blood],
                   cardImageName: "B12-054.png")

let b12_059 = Card(series: "B12-059SR",
                   name: "Playful Millenary Dragon, Nowi",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 20,
                   illustrator: "Kawasumi",
                   supportingSkill: none,
                   skills: [nowis_treasure, longevous_dragonkin],
                   cardImageName: "B12-059.png")

let b12_070 = Card(series: "B12-070HN",
                   name: "The Conqueror's Tactician, Excellus",
                   rarity: "High Normal",
                   insignia: mark_of_naga,
                   attack: 50,
                   support: 20,
                   illustrator: "Yoneko",
                   supportingSkill: none,
                   skills: [manipulative_tactics, do_not_interfere_2],
                   cardImageName: "B12-070.png")

let b12_071 = Card(series: "B12-071SR",
                   name: "God-Surpassing Conqueror, Walhart",
                   rarity: "Secret Rare",
                   insignia: mark_of_naga,
                   attack: 70,
                   support: 10,
                   illustrator: "Azusa",
                   supportingSkill: none,
                   skills: [devastation, conquest, regnant],
                   cardImageName: "B12-071.png")

let b12_072 = Card(series: "B12-072N",
                   name: "Emperor of Valm, Walhart",
                   rarity: "Normal",
                   insignia: mark_of_naga,
                   attack: 60,
                   support: 10,
                   illustrator: "Azusa",
                   supportingSkill: attack_emblem,
                   skills: [i_am_inexorable, do_not_interfere],
                   cardImageName: "B12-072.png")

let b12_073 = Card(series: "B12-073R",
                   name: "Naga: Divine Dragon of Salvation",
                   rarity: "Rare",
                   insignia: mark_of_naga,
                   attack: 0,
                   support: 20,
                   illustrator: "Aoji",
                   supportingSkill: none,
                   skills: [divine_dragons_rite_of_awakening, nagas_power],
                   cardImageName: "B12-073.png")

let b12_074 = Card(series: "B12-074HN",
                   name: "Risen Chief: Grotesque Commander",
                   rarity: "High Normal",
                   insignia: mark_of_naga,
                   attack: 0,
                   support: 0,
                   illustrator: "cuboon",
                   supportingSkill: none,
                   skills: [commander_of_corpses, corpse_calling_corpse, reeking_miasma],
                   cardImageName: "B12-074.png")

let b13_001 = Card(series: "B13-001SR",
                   name: "Eliwood: Blazing Knight of Valor",
                   rarity: "Secret Rare",
                   insignia: divine_weapons,
                   attack: 70,
                   support: 20,
                   illustrator: "Rika Suzuki",
                   supportingSkill: undying_friendship,
                   skills: [durandals_true_flames, crimson_sovereign],
                   cardImageName: "B13-001.png")

let b13_004 = Card(series: "B13-004SR",
                   name: "Lyn: Blade Princess of the Spring Breeze",
                   rarity: "Secret Rare",
                   insignia: divine_weapons,
                   attack: 70,
                   support: 0,
                   illustrator: "Rika Suzuki",
                   supportingSkill: memories_of_the_earth,
                   skills: [staunchflash_sol_katti, lend_me_your_strength],
                   cardImageName: "B13-004.png")

let b13_019 = Card(series: "B13-019SR",
                   name: "Hector: General of Raging Thunder",
                   rarity: "Secret Rare",
                   insignia: divine_weapons,
                   attack: 80,
                   support: 10,
                   illustrator: "Rika Suzuki",
                   supportingSkill: eternal_friendship,
                   skills: [armads_almighty_lightning],
                   cardImageName: "B13-019.png")

let b13_051 = Card(series: "B13-051SR",
                   name: "Marth: Hero Chosen by the Exalted Blade",
                   rarity: "Secret Rare",
                   insignia: blade_of_light,
                   attack: 70,
                   support: 20,
                   illustrator: "Daisuke Izuka",
                   supportingSkill: none,
                   skills: [on_the_path_to_victory, conquest_in_the_name_of_the_hero_king, falchion],
                   cardImageName: "B13-051.png")

let b13_055 = Card(series: "B13-055R",
                   name: "Abel: Panther of the Adept Lance",
                   rarity: "Rare",
                   insignia: blade_of_light,
                   attack: 70,
                   support: 10,
                   illustrator: "Aoji",
                   supportingSkill: none,
                   skills: [green_and_red_paladins, panthers_formation, my_life_is_my_princes],
                   cardImageName: "B13-055.png")

let b13_057 = Card(series: "B13-057HN",
                   name: "Frey: Death-Defying Paladin",
                   rarity: "High Normal",
                   insignia: blade_of_light,
                   attack: 60,
                   support: 10,
                   illustrator: "Nijihayashi",
                   supportingSkill: none,
                   skills: [knowledge_vital_to_a_knight, duty_to_defend],
                   cardImageName: "B13-057.png")

let b13_060 = Card(series: "B13-060R",
                   name: "Cain: Bull of the War Sword",
                   rarity: "Rare",
                   insignia: blade_of_light,
                   attack: 70,
                   support: 10,
                   illustrator: "Karuta Shiki",
                   supportingSkill: none,
                   skills: [red_and_green_paladins, bulls_charge, my_life_is_my_princes],
                   cardImageName: "B13-060.png")

let b13_064 = Card(series: "B13-064R",
                   name: "Draug: Guardian God of Altea",
                   rarity: "Rare",
                   insignia: blade_of_light,
                   attack: 60,
                   support: 10,
                   illustrator: "Homazo",
                   supportingSkill: none,
                   skills: [guardian_gods_gallant_guise, armor_expertise],
                   cardImageName: "B13-064.png")

let b13_066 = Card(series: "B13-066R",
                   name: "Norne: Crisis-Headlong Bow",
                   rarity: "Rare",
                   insignia: blade_of_light,
                   attack: 50,
                   support: 20,
                   illustrator: "Sakura Miwabe",
                   supportingSkill: none,
                   skills: [patriotic_volunteer, heh_oops_uhh, wingbane],
                   cardImageName: "B13-066.png")

let b13_070 = Card(series: "B13-070R",
                   name: "Lena: Angel of Noble Love",
                   rarity: "Rare",
                   insignia: blade_of_light,
                   attack: 60,
                   support: 20,
                   illustrator: "daigoman",
                   supportingSkill: none,
                   skills: [blessing_of_gentle_love, purifying_halo],
                   cardImageName: "B13-070.png")

let b13_088 = Card(series: "B13-088R",
                   name: "Kiran: Otherworldly Great Hero",
                   rarity: "Rare",
                   insignia: colorless,
                   attack: 0,
                   support: 0,
                   illustrator: "Clover.K",
                   supportingSkill: salvations_command,
                   skills: [summoning_weapon_breidablik],
                   cardImageName: "B13-088.png")

let b13_089 = Card(series: "B13-089N",
                   name: "Kiran: Legendary Hero",
                   rarity: "Normal",
                   insignia: colorless,
                   attack: 0,
                   support: 0,
                   illustrator: "Clover.K",
                   supportingSkill: divine_weapon_of_summoning,
                   skills: [summon_heroes],
                   cardImageName: "B13-089.png")
