//
//  Illustrators.swift
//  Cipher TCG
//
//  Created by Dylan Rothfeld on 11/17/18.
//  Copyright © 2018 Dylan Rothfeld. All rights reserved.
//

import UIKit

let unknown = Illustrator(name: "Unknown")
let yusuke_kozaki = Illustrator(name: "Yusuke Kozaki")
let clover_k = Illustrator(name: "Clover K")
let fuzichoco = Illustrator(name: "Fuzichoco")
let senri_kita = Illustrator(name: "Senri Kita")
let masaki_hirooka = Illustrator(name: "Masaki Hirooka")
let bisai = Illustrator(name: "BISAI")
let yang_yang = Illustrator(name: "YangYang")
let pisuke = Illustrator(name: "Pisuke")
let kaoru_hagiya = Illustrator(name: "Kaoru Hagiya")
let rika_suzuki = Illustrator(name: "Rika Suzuki")
let mayo = Illustrator(name: "Mayo")
let tetsu_kurosawa = Illustrator(name: "Tetsu Kurosawa")
let haccan = Illustrator(name: "HACCAN")
let cuboon = Illustrator(name: "cuboon")
let daisuke_izuka = Illustrator(name: "Daisuke Izuka")
let raita_kazama = Illustrator(name: "Raita Kazama")
let ayaka_suzuki = Illustrator(name: "Ayaka Suzuki")
let mikihiro_taguchi = Illustrator(name: "Mikihiro Taguchi")
let daigoman = Illustrator(name: "Daigoman")
let maki_hakoda = Illustrator(name: "Maki Hakoda")
let lack = Illustrator(name: "Lack")
let sachiko_wada = Illustrator(name: "Sachiko Wada")
let aoji = Illustrator(name: "Aoji")
let saori_toyota = Illustrator(name: "Saori Toyota")
let hara = Illustrator(name: "40hara")
let tada = Illustrator(name: "Tada")
let yoko_maturica = Illustrator(name: "Yoko Maturica")
let kokon_konfuzi = Illustrator(name: "Kokon Konfuzi")
let minori_fuyuzora = Illustrator(name: "Minori Fuyuzora")
let kotaro_yamada = Illustrator(name: "Kotaro Yamada")
let setsu = Illustrator(name: "Setsu")
let yamada_kotarou = Illustrator(name: "Yamada Kotarou")
let aogachou = Illustrator(name: "aogachou")
let ryuutetu = Illustrator(name: "Ryuutetu")
let hmk = Illustrator(name: "HMK84")
let sakura_miwabe = Illustrator(name: "Sakura Miwabe")
let yoneko = Illustrator(name: "Yoneko")
let geso_umiu = Illustrator(name: "Geso Umiu")
let tomohide_takaya = Illustrator(name: "Tomohide Takaya")
let nekobayashi = Illustrator(name: "Nekobayashi")
let nnekora = Illustrator(name: "nNekoRa")
let fumi_hasumi = Illustrator(name: "Fumi Hasumi")
let azusa = Illustrator(name: "Azusa")
let kawasumi = Illustrator(name: "Kawasumi")
let akira_fujikawa = Illustrator(name: "Akira Fujikawa")
let niji = Illustrator(name: "Niji")
let genki_kuno = Illustrator(name: "Genki Kuno")
let karuta_shiki = Illustrator(name: "Karuta Shiki")
let niko_komori = Illustrator(name: "Niko Komori")
let nijihayashi = Illustrator(name: "Nijihayashi")
let akihiro_mibuta = Illustrator(name: "Akihiro Mibuta")
let homazo = Illustrator(name: "Homazo")
let yugo_okuma = Illustrator(name: "Yugo Okuma")
let kotetsu_kinoshita = Illustrator(name: "Kotetsu Kinoshita")
let megumi_nagahama = Illustrator(name: "Megumi Nagahama")
let kitsunen_kurodan = Illustrator(name: "Kitsunen Kurodan")
let kazuhiro_taneda = Illustrator(name: "Kazuhiro Taneda")
let misei_ito = Illustrator(name: "Misei Ito")
let sachie = Illustrator(name: "Sachie")
let horiguchi_kousei = Illustrator(name: "Horiguchi Kousei")
let enji_kazura = Illustrator(name: "Enji Kazura")
let tobi = Illustrator(name: "Tobi")
let shigetaka_kimura = Illustrator(name: "Shigetaka Kimura")
let tatsuro_iwamoto = Illustrator(name: "Tatsuro Iwamoto")
let mineri = Illustrator(name: "Mineri")
let uroko_naruse = Illustrator(name: "Uroko Naruse")
let ippei_soeda = Illustrator(name: "Ippei Soeda")
let douji_shiki = Illustrator(name: "Douji Shiki")
let foo_midori = Illustrator(name: "Foo Midori")
let mattsun = Illustrator(name: "Mattsun")
let simadoriru = Illustrator(name: "Simadoriru")
let cherokee = Illustrator(name: "Cherokee")
let hatori_kyoka = Illustrator(name: "Hatori Kyoka")
let shidzuki = Illustrator(name: "Shidzuki")
let kureta = Illustrator(name: "Kureta")
let misa_tsutsui = Illustrator(name: "Misa Tsutsui")
let shishizaru = Illustrator(name: "Shishizaru")
let meisai = Illustrator(name: "Meisai")
let enomoto = Illustrator(name: "Enomoto")
let hatapug = Illustrator(name: "Hatapug")
let eiji_kaneda = Illustrator(name: "Eiji Kaneda")
let yoshiro_ambe = Illustrator(name: "Yoshiro Ambe")
let mari_shimazaki = Illustrator(name: "Mari Shimazaki")
let mio_itou = Illustrator(name: "Mio Itou")
let momori = Illustrator(name: "Momori")
let sora_amamiya = Illustrator(name: "Sora Amamiya")
let kyo_uda = Illustrator(name: "Kyo Uda")

